# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DevExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DevExample
  pod 'MobileCenter/Crashes', '~> 0.11.2'
  pod 'MobileCenter/Analytics', '~> 0.11.2'
  pod 'RNMobileCenterShared', '~> 0.8.1'

  

  target 'DevExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DevExample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DevExample-tvOS

  target 'DevExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
